### PR TITLE
Fix paragraph tag in javadoc

### PR DESCRIPTION
**Pull request by Drepic26**
Gradle was throwing an error during build because of these incorrect paragraph tags:

ss 2015-01-23 at 10 59 37

### CODE REVIEW

**Comment by gravitylow** [comment]
Interesting. Thanks for the PR!

**Comment by feildmaster** [comment]
So gradle doesn't allow for valid HTML?

**Comment by Drepic26** [comment]
[As of HTML5 (as far as I am aware) only void elements are allowed to be self closing.](http://www.w3.org/TR/html5/syntax.html#elements-0)

**Comment by feildmaster** [comment]
Hmm... javadocs don't normally generate in HTML5.

Also that's supposed to be 2 paragraphs (after the first line). You made it one paragraph and a footnote.

**Comment by Drepic26** [comment]
So javadocs do generate with HTML 4.01, I was wrong there.  Although self closing paragraph tags are accepted by the W3C validator, `<p/>` will be the same as the `<p>` tag since HTML parsers simply ignore the slash. If that is the case, then the bottom tag should be changed from `</p>` to `<p>`. <br>
I don't see any difference the way it is now however.  Above is generated from the change I made, the below is what I saw hosted [here.](http://gravitydevelopment.net/docs/updater/) However, if it was intended to be two paragraphs, then the closing tag should be changed.
ss 2015-01-29 at 09 33 00 As far as I can tell there is no difference. <br>
I apologize if I did mess up the formatting somewhere, but the point of this PR was to bring attention to the error thrown for the sake of anyone using Gradle. I recommend that [this](https://github.com/gravitylow/Updater/pull/26/files#diff-8fbc15ee4d6fdd27b5e169640f6b181dR27) tag be changed to `<p>` anyway, to change it to the intended two paragraphs.

**Pull request merged**
